import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="flex flex-col min-h-screen">
          <header className="bg-gray-800 text-white p-4">
            <h1 className="text-2xl font-bold">
              Memory Visualization & Pass By Demo
            </h1>
          </header>
          <main className="flex-1 p-4">{children}</main>
          <footer className="bg-gray-800 text-white p-4 text-center">
            &copy; {new Date().getFullYear()} Your App Name
          </footer>
        </div>
      </body>
    </html>
  );
}
